version: "3.8"
services:
  milvus:
    image: milvusdb/milvus:v2.2.12
    container_name: milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    volumes:
      - ./volumes/milvus:/var/lib/milvus
    environment:
      - "TZ=UTC"
    command: ["milvus", "standalone"]